version: '3.5'
services:
#
#  fraud:
#    container_name: fraud
#    image: marricode/fraud:1.2
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - postgres
#      - spring
#    depends_on:
#      - eureka-server
#      - postgres
#      - zipkin
#      - rabbitmq
#
#  customer:
#    container_name: customer
#    image: marricode/customer:1.2
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - postgres
#      - spring
#    depends_on:
#      - eureka-server
#      - zipkin
#      - postgres
#      - rabbitmq
#
#  notification:
#    container_name: notification
#    image: marricode/notification:1.2
#    ports:
#      - "8086:8086"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - postgres
#      - spring
#    depends_on:
#      - zipkin
#      - rabbitmq
#      - postgres
#      - eureka-server
#
#  eureka-server:
#    container_name: eureka-server
#    image: marricode/eureka-server:1.2
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#
#  apigw:
#    container_name: apigw
#    image: marricode/apigw:1.2
#    ports:
#      - "8090:8090"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - eureka-server
#      - zipkin

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: 'neofoxcool@gmail.com'
      POSTGRES_PASSWORD: '1993'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'neofoxcool@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '1993'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: