server:
  port: 8086
spring:
  application:
    name: notification
  datasource:
    username: 'neofoxcool@gmail.com'
    password: '1993'
    url: jdbc:postgresql://192.168.99.100:5432/notification
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://192.168.99.100:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone:  http://localhost:8761/eureka
    enabled: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key