server:
  port: 8090
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/registering/**
  zipkin:
    base-url: http://zipkin:9411


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-server:8761/eureka

