server:
  port: 8083

spring:
  application:
    name: API-GateWay
  zipkin:
    base-url: "http://zipkin:9411"
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/registering/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone:  'http://eureka-server:8761/eureka'