server:
  port: 8090
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/registering/**
  zipkin:
    base-url: http://zipkin:9411

eureka:
  host: eureka-server
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: true

