server:
  port: 8761
spring:
  application:
    name: eureka_server

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false
  service-url:
    default-zone: http://localhost:8761/eureka