server:
  port: 8761
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411

eureka:
  base-url: http://eureka-server:8761/eureka
  client:
    fetch-registry: false
    register-with-eureka: false
  service-url:
    default-zone: http://eureka-server:8761/eureka



